###############################################################################
##        Name: alpine/stress_test                                            #
##        Date: 18/11/2020                                                    #
## Description: Basic dockerfile to execute the script stress_test.sh         #
##              over Alpine.                                                  #
##----------------------------------------------------------------------------#
##      Editor: José Manuel Plana Santos                                      #
##     Contact: dev.josemanuelps@gmail.com                                    #
###############################################################################



FROM alpine:3.12.3

# Update and install main packages.
RUN apk update && apk add bash stress-ng

ENV STTIME=10

# Copy stress_test.sh script.
COPY ./stress_test.sh ./stress_test.sh
RUN chmod +x ./stress_test.sh

# Default execution.
CMD ["/bin/bash", "-c", "./stress_test.sh"]


