###############################################################################
##        Name: stress_test                                                   #
##        Date: 18/11/2020                                                    #
##     Version: v1.0                                                          #
## Description: A simple dockerfile, which runs a script to perform a stress  #
##              test to check CPU, RAM, Network and Disk.                     #
##----------------------------------------------------------------------------#
##      Editor: José Manuel Plana Santos                                      #
##     Contact: dev.josemanuelps@gmail.com                                    #
###############################################################################



FROM alpine:3.12.3

# Update and install main packages.
RUN apk update && apk add bash stress-ng

ENV STTIME=10

# Copy stress_test.sh script.
COPY ./stress_test.sh ./stress_test.sh
RUN chmod +x ./stress_test.sh

# Default execution.
CMD ["/bin/bash", "-c", "./stress_test.sh"]


