###############################################################################
##        Name: ssh                                                           #
##        Date: 12/12/2020                                                    #
##     Version: v1.0                                                          #
## Description: A simple dockerfile, which runs a simple container with the   #
##              ssh service exposed.                                          #
##----------------------------------------------------------------------------#
##      Editor: José Manuel Plana Santos                                      #
##     Contact: dev.josemanuelps@gmail.com                                    #
###############################################################################



FROM ubuntu:21.04

# Update and install main packages.
RUN apt -y update && apt -y install openssh-server

# Expose port:
EXPOSE 22

RUN mkdir -p /var/run/sshd
RUN ssh-keygen -A
RUN mkdir -p /root/.ssh/
COPY ./ssh_key.pub /root/.ssh/ssh_key.pub
RUN cat /root/.ssh/ssh_key.pub > /root/.ssh/authorized_keys

# TODO: Type some password before build.
RUN echo "root:<(some_password)>" | chpasswd

# Default execution.
CMD ["/usr/sbin/sshd", "-D"]


